"""Shared structural constants for one generated flashcard module."""

CONCEPTS_PER_MODULE = 20
CLUSTERS_PER_MODULE = CONCEPTS_PER_MODULE
CARDS_PER_CLUSTER = 5
BLOCKS_PER_MODULE = 2
CLUSTERS_PER_BLOCK = CLUSTERS_PER_MODULE // BLOCKS_PER_MODULE
CARDS_PER_BLOCK = CLUSTERS_PER_BLOCK * CARDS_PER_CLUSTER
CARDS_PER_MODULE = CLUSTERS_PER_MODULE * CARDS_PER_CLUSTER
